module github.com/martianoff/gala_team

go 1.25.5

require github.com/google/uuid v1.6.0 // indirect

// GALA-managed Go dependencies below. DO NOT EDIT.
// Generated by 'gala mod tidy'. Use 'gala build' or 'bazel build' to compile.
require (
	github.com/google/uuid v1.6.0
)
// End GALA-managed dependencies.

